apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: drop-cap-net-raw
  annotations:
    policies.kyverno.io/title: Drop CAP_NET_RAW
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.5.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Capabilities permit privileged actions without giving full root access. The
      CAP_NET_RAW capability, enabled by default, allows processes in a container to
      forge packets and bind to any interface potentially leading to MitM attacks.
      This policy ensures that all containers explicitly drop the CAP_NET_RAW
      ability.      
spec:
  validationFailureAction: audit
  background: false
  rules:
  - name: drop-cap-net-raw-initcontainers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
      # Check if initContainers even exist in the Pod.
      - key: "{{ request.object.spec.initContainers[] | length(@) }}"
        operator: GreaterThanOrEquals
        value: 1
    validate:
      message: The capability CAP_NET_RAW must be explicitly dropped.
      foreach:
      - list: "request.object.spec.initContainers[].securityContext.capabilities"
        deny:
          conditions:
            any:
            # Loop over the `drop[]` array in each container looking for `CAP_NET_RAW` and deny if not found.
            - key: "{{ element.drop  | contains(@, 'CAP_NET_RAW') }}"
              operator: Equals
              value: false
            # Also deny if every container in the Pod doesn't specify the `drop[]` array (doesn't exist).
            - key: "{{request.object.spec.initContainers[].securityContext.capabilities.drop | length(@) }}"
              operator: NotEquals
              value: "{{request.object.spec.initContainers[] | length(@) }}"
  - name: drop-cap-net-raw-containers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: The capability CAP_NET_RAW must be explicitly dropped.
      foreach:
      - list: "request.object.spec.containers[].securityContext.capabilities"
        deny:
          conditions:
            any:
            # Loop over the `drop[]` array in each container looking for `CAP_NET_RAW` and deny if not found.
            - key: "{{ element.drop  | contains(@, 'CAP_NET_RAW') }}"
              operator: Equals
              value: false
            # Also deny if every container in the Pod doesn't specify the `drop[]` array (doesn't exist).
            - key: "{{request.object.spec.containers[].securityContext.capabilities.drop | length(@) }}"
              operator: NotEquals
              value: "{{request.object.spec.containers[] | length(@) }}"