policies:
- name: restrict-secrets-by-name
  rules:
  - name: safe-secrets-from-volumes
  - name: safe-secrets-from-env
  - name: safe-secrets-from-envfrom
  resources:
  - name: good-pod-all
    values:
      request.operation: CREATE
  - name: bad-pod-vol
    values:
      request.operation: CREATE
  - name: bad-pod-env
    values:
      request.operation: CREATE
  - name: bad-pod-envfrom
    values:
      request.operation: CREATE
  - name: bad-deploy-env
    values:
      request.operation: CREATE
  - name: bad-deploy-envfrom
    values:
      request.operation: CREATE
  - name: bad-deploy-vol
    values:
      request.operation: CREATE
