apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  automountServiceAccountToken: false
  initContainers:
  - name: alpine
    image: registry.io/alpine:latest
  - name: busybox
    image: registry.io/busybox:1.28
  containers:
  - name: nginx
    image: registry.io/nginx:1.2.3
  - name: redis
    image: registry.io/redis:latest